### ISSUE TITLE
Controlling the training direction

### ISSUE THREAD

**Issue by AndroYD84** [kingsj0405/ciplab-NTIRE-2020#1]
I'm extremely impressed with your results, it's much better than anything I've used before, do you think this project could be suitable for other restoration tasks as well such as deblurring/noise removal?
The readme mentions that the training procedure requires to add all pictures into one folder (ie. "./train") and run train.py, however originally ESRGAN required at least two folders (LR and HR) to guide the training in the desired direction (A to B/LR to HR logic), from experience I learned that it was possible to guide it to fix other kind of problems simply by adding the problematic pictures in the LR folder and the desired outcome in the HR folder, even thought it wasn't originally made for fixing many of those very specific problems (ie. artifacts) it did a pretty good job at them, so I was wondering if this project could potentially do an even better job at this? Any opinions?

**Comment by yhjo09** [comment]
Hi, thanks for your interest.
We proposed a loss function and this can be attached to any deep networks.
We expect that our loss can affect other restoration tasks for improving perceptual quality.
As our task is x16 SR, our code reads HR images in "./train" and downsample them 1/16 to generate LR images, and LR-HR patch pairs are used for training.
But it is possible to use distorted LR images from "./LR" and target HR images from "./HR" by modifying the code.
