### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by scutlrr** [kingsj0405/ciplab-NTIRE-2020#2]
in LPIPS/network_basic.py, for line 96，why is:

 `if(self.pnet_tune):`
      `self.net = net_type(pretrained=not self.pnet_rand,requires_grad=True)`
`else:`
      `self.net = [net_type(pretrained=not self.pnet_rand,requires_grad=**True**),]`
is not it:
`if(self.pnet_tune):`
      `self.net = net_type(pretrained=not self.pnet_rand,requires_grad=True)`
`else:`
      `self.net = [net_type(pretrained=not self.pnet_rand,requires_grad=**False**),]`

**Comment by flybiubiu** [comment]
> in LPIPS/network_basic.py, for line 96，why is:
> 
> `if(self.pnet_tune):`
> `self.net = net_type(pretrained=not self.pnet_rand,requires_grad=True)`
> `else:`
> `self.net = [net_type(pretrained=not self.pnet_rand,requires_grad=**True**),]`
> is not it:
> `if(self.pnet_tune):`
> `self.net = net_type(pretrained=not self.pnet_rand,requires_grad=True)`
> `else:`
> `self.net = [net_type(pretrained=not self.pnet_rand,requires_grad=**False**),]`

Hi!See you again！From TTSR
Can we change wechat?

**Comment by kingsj0405** [comment]
It seems your correction is right.

**Comment by scutlrr** [comment]
@flybiubiu LRR5235.
