### ISSUE TITLE
Datashet load question

### ISSUE THREAD

**Issue by duweihua** [kingsj0405/ciplab-NTIRE-2020#4]
Using  the DIV2K traing set(800) to train the mode,but  the code can not normal load the  dataset.Always stop in this state.Why?(windows 10)

  0%|          | 0/150000 [00:00<?, ?it/s]Found 800 trainnig images
===> Training start

**Comment by kingsj0405** [comment]
It seems path error because of environment(windows 10). You can try replace `os.path` to `pathlib`.
