### ISSUE TITLE
PSNR and LPIPS

### ISSUE THREAD

**Issue by flybiubiu** [kingsj0405/ciplab-NTIRE-2020#8]
why result so different？
<img width="1413" alt="Screen Shot 2021-01-07 at 4 22 08 PM" src="https://user-images.githubusercontent.com/20927755/103868894-80597f00-5104-11eb-86b1-54e75043b3fa.png">
<img width="710" alt="Screen Shot 2021-01-07 at 4 25 07 PM" src="https://user-images.githubusercontent.com/20927755/103869160-e9d98d80-5104-11eb-9990-98e9e94be7da.png">

 Is Validation with Y channel?

**Comment by kingsj0405** [comment]
Did you initialize generator?
You need to train generator with MSE loss only at first.

**Comment by flybiubiu** [comment]
> Did you initialize generator?
> You need to train generator with MSE loss only at first.

yes!I run this code without any change.

START_ITER = 0      # Set 0 for from scratch, else will load saved params and trains further
NB_ITER_MSE = 75000 # MSE pretraining iteration, after that the full loss works
NB_ITER = 150000    # Total number of training iterations

**Comment by yhjo09** [comment]
Hi,
Those numbers were calculated from the challenge organizers, and the test images are different from our validation images.
